// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.2
// source: proto/products.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "products";

export interface GetProductsRequest {
  productId: number;
  productIddd: number;
}

export interface GetProductsResponse {
  productId: number;
  name: string;
  price: number;
}

export const PRODUCTS_PACKAGE_NAME = "products";

export interface ProductsClient {
  getProducts(request: GetProductsRequest): Observable<GetProductsResponse>;
}

export interface ProductsController {
  getProducts(
    request: GetProductsRequest,
  ): Promise<GetProductsResponse> | Observable<GetProductsResponse> | GetProductsResponse;
}

export function ProductsControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["getProducts"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("Products", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("Products", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const PRODUCTS_SERVICE_NAME = "Products";
